name: paa
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - adjusttext=0.7.3.1
  - alabaster=0.7.12
  - applaunchservices=0.2.1
  - appnope=0.1.0
  - argh=0.26.2
  - astroid=2.4.1
  - atomicwrites=1.4.0
  - attrs=19.3.0
  - autopep8=1.4.4
  - babel=2.8.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.4
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - cloudpickle=1.4.1
  - cryptography=2.9.2
  - cycler=0.10.0
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - descartes=1.1.0
  - diff-match-patch=20181111
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.6
  - flake8=3.8.2
  - freetype=2.9.1
  - future=0.18.2
  - gettext=0.19.8.1
  - glib=2.63.1
  - icu=58.2
  - idna=2.9
  - imagesize=1.2.0
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - intel-openmp=2019.4
  - intervaltree=3.0.2
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jedi=0.15.2
  - jinja2=2.11.2
  - joblib=0.15.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - keyring=21.1.1
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - libcxx=10.0.0
  - libedit=3.1.20181209
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libpng=1.6.37
  - libsodium=1.0.16
  - libspatialindex=1.9.3
  - llvm-openmp=10.0.0
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mizani=0.7.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - mpld3=0.3
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - numpydoc=0.9.2
  - openssl=1.1.1g
  - packaging=20.3
  - palettable=3.3.0
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.2
  - pathtools=0.1.2
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - plotnine=0.7.0
  - pluggy=0.13.1
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - psutil=5.7.0
  - ptyprocess=0.6.0
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydocstyle=4.0.1
  - pyflakes=2.2.0
  - pygments=2.6.1
  - pylint=2.5.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.31.9
  - python.app=2
  - python_abi=3.6
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=18.1.1
  - qdarkstyle=2.8.1
  - qt=5.9.7
  - qtawesome=0.7.0
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.23.0
  - rope=0.17.0
  - rtree=0.9.4
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.1
  - setuptools=47.1.1
  - sip=4.19.8
  - six=1.15.0
  - snowballstemmer=2.0.0
  - sortedcontainers=2.1.0
  - sphinx=3.0.4
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=4.1.3
  - spyder-kernels=1.9.1
  - sqlite=3.31.1
  - statsmodels=0.11.1
  - testpath=0.4.4
  - tk=8.6.8
  - toml=0.10.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - ujson=1.35
  - urllib3=1.25.8
  - watchdog=0.10.2
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - wrapt=1.11.2
  - wurlitzer=2.0.0
  - xlrd=1.2.0
  - xz=5.2.5
  - yaml=0.1.7
  - yapf=0.28.0
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
prefix: /Users/avasoleimany/miniconda3/envs/paa
